apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: thumbnail-worker
  name: thumbnail-worker
spec:
  replicas: 3
  selector:
      matchLabels:
        name: thumbnail-worker
  template:
    metadata:
      labels:
        name: thumbnail-worker
    spec:
      containers:
      - name: thumbnail-worker
        image: gcr.io/yash-innovation/thumbnail-worker:latest
        tty: true
        env:
        - name: PROJECT_ID
          value: "yash-innovation"
        - name: DB_USER
          value: "appuser"
        - name: DB_PASS
          value: "pas4appuser"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=yash-innovation:us-central1:photoalbum-db20=tcp:3306"]
        securityContext:
          runAsUser: 2
          allowPrivilegeEscalation: false
