apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: photoalbum-app
  name: photoalbum-app
spec:
  replicas: 3
  selector:
      matchLabels:
        name: photoalbum-app
  template:
    metadata:
      labels:
        name: photoalbum-app
    spec:
      containers:
      - name: photoalbum-app
        image: gcr.io/yash-innovation/photoalbum-app:latest
        tty: true
        ports:
        - containerPort: 8080
        env:
        - name: PROJECT_ID
          value: "yash-innovation"
        - name: DB_USER
          value: "appuser"
        - name: DB_PASS
          value: "pas4appuser"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=yash-innovation:us-central1:photoalbum-db18=tcp:3306"]
        securityContext:
          runAsUser: 2
          allowPrivilegeEscalation: false
